# Generated by Django 4.2.1 on 2023-06-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geometrycoordinatesmodel',
            name='plane',
            field=models.CharField(default='XY', max_length=2),
        ),
    ]
